#pragma once

NTSTATUS
FilterLoad(PDRIVER_OBJECT driver_obj);

NTSTATUS
FilterUnload(FLT_FILTER_UNLOAD_FLAGS flags);

FLT_PREOP_CALLBACK_STATUS
PrevCreateRoutine(PFLT_CALLBACK_DATA data, PCFLT_RELATED_OBJECTS flt_obj, PVOID* context);

FLT_POSTOP_CALLBACK_STATUS
PostCreateRoutine(PFLT_CALLBACK_DATA data, PCFLT_RELATED_OBJECTS flt_obj, PVOID context, FLT_POST_OPERATION_FLAGS flags);